export const personalInfo = {
  name: "Isni Skara",
  title: "AI Automation & Vibe Code Specialist",
  tagline: "Where human reasoning meets autonomous systems.",
  location: "North Macedonia",
  linkedin: "https://linkedin.com/in/isniskara",
  email: "contact@example.com", // Placeholder - update before deployment
};

export const skills = [
  {
    id: "python",
    name: "Python Scripting & Automation",
    shortName: "Python",
    description: "Data processing, validation pipelines, and automation scripts",
    icon: "Code2",
    status: "active",
    category: "core",
  },
  {
    id: "scraping",
    name: "Web Scraping & Data Extraction",
    shortName: "Web Scraping",
    description: "BeautifulSoup, Selenium, APIs, dynamic page handling",
    icon: "Globe",
    status: "active",
    category: "core",
  },
  {
    id: "data",
    name: "Data Processing & QA",
    shortName: "Data QA",
    description: "CSV, JSON normalization, verification, quality assurance",
    icon: "Database",
    status: "active",
    category: "core",
  },
  {
    id: "llm",
    name: "LLMs & AI Automation",
    shortName: "LLMs & AI",
    description: "RAG pipelines, AI evaluation frameworks, prompt engineering",
    icon: "Brain",
    status: "active",
    category: "ai",
  },
  {
    id: "agents",
    name: "AI Agents & Orchestration",
    shortName: "AI Agents",
    description: "Multi-agent systems, workflow automation, autonomous pipelines",
    icon: "Bot",
    status: "active",
    category: "ai",
  },
  {
    id: "n8n",
    name: "Workflow Orchestration (n8n)",
    shortName: "n8n",
    description: "Event tracking, monitoring, analytics workflows",
    icon: "Workflow",
    status: "active",
    category: "automation",
  },
  {
    id: "backend",
    name: "Backend Engineering",
    shortName: "Backend",
    description: "Node.js, TypeScript, PHP, scalable systems",
    icon: "Server",
    status: "active",
    category: "engineering",
  },
  {
    id: "api",
    name: "APIs & Integrations",
    shortName: "APIs",
    description: "REST APIs, data pipelines, third-party integrations",
    icon: "Plug",
    status: "active",
    category: "engineering",
  },
  {
    id: "research",
    name: "Research & Validation",
    shortName: "Research",
    description: "Advanced web research, source validation, data accuracy",
    icon: "Search",
    status: "active",
    category: "core",
  },
  {
    id: "docs",
    name: "Documentation & Reproducibility",
    shortName: "Documentation",
    description: "Clear documentation, reproducible workflows, knowledge transfer",
    icon: "FileText",
    status: "active",
    category: "engineering",
  },
];

export const experience = [
  {
    id: "aivi",
    company: "AIVI",
    role: "AI Backend Infrastructure Engineer",
    type: "Full-time",
    period: "Nov 2024 - Present",
    location: "Remote",
    isActive: true,
    responsibilities: [
      "Designed and implemented high-availability AI automation systems with multiple AI providers and fallback logic",
      "Built data pipelines and RAG/ML evaluation frameworks to benchmark AI provider performance",
      "Developed event tracking, monitoring, and analytics workflows using n8n",
      "Implemented structured data ingestion and processing pipelines",
      "Created reproducible orchestration templates for AI-driven workflows",
    ],
    technologies: ["Python", "LLMs", "RAG", "n8n", "Data Pipelines", "AI Agents"],
    relevance: "AI agents, LLM workflows, data validation, automation, reproducibility, QA",
  },
  {
    id: "discord",
    company: "Discord Ventures",
    role: "Chief Technology Officer",
    type: "Full-time",
    period: "Jan 2024 - Present",
    location: "Remote",
    isActive: true,
    responsibilities: [
      "Led technical strategy for automation-first platforms and AI-assisted workflows",
      "Oversaw data-driven research, extraction, and processing pipelines",
      "Designed scalable backend systems emphasizing data accuracy and validation",
      "Evaluated and implemented AI tools to accelerate research and automation",
    ],
    technologies: ["Strategic Architecture", "AI Tooling", "Data Pipelines", "Automation"],
    relevance: "Strategic problem-solving, independent execution, AI tooling, cross-domain adaptability",
  },
  {
    id: "ecoreis",
    company: "ECO REIS",
    role: "Head of Technology",
    type: "Full-time",
    period: "Mar 2021 - Sep 2023",
    location: "Remote (US)",
    isActive: false,
    responsibilities: [
      "Led development of automation workflows and data integration systems",
      "Built and maintained data extraction pipelines from third-party systems and APIs",
      "Implemented process automation reducing manual workload",
      "Ensured systems followed strict data structure and verification requirements",
    ],
    technologies: ["Automation", "APIs", "Data Integration", "Process Optimization"],
    relevance: "Data pipelines, automation, API integration, quality assurance",
  },
  {
    id: "bomb",
    company: "Bomb CRM",
    role: "Senior Developer",
    type: "Full-time",
    period: "Oct 2020 - Jan 2023",
    location: "Remote",
    isActive: false,
    responsibilities: [
      "Developed PHP and API-based automation solutions integrating third-party platforms",
      "Created structured data flows across CRM systems with validation",
      "Built automation logic using Podio & Globiflow",
      "Provided technical support for complex automation workflows",
    ],
    technologies: ["PHP", "APIs", "Podio", "Globiflow", "CRM Systems"],
    relevance: "APIs, structured data, automation logic, troubleshooting, documentation",
  },
  {
    id: "aa",
    company: "AA Real Estate Group",
    role: "Director of Technology Development",
    type: "Full-time",
    period: "Feb 2021 - Oct 2022",
    location: "US (Remote)",
    isActive: false,
    responsibilities: [
      "Managed IT infrastructure, automation strategy, and system integrations",
      "Designed data workflows and reporting systems for operational decisions",
      "Automated business processes ensuring system reliability",
    ],
    technologies: ["IT Infrastructure", "Automation", "Reporting Systems"],
    relevance: "Infrastructure management, automation strategy, data workflows",
  },
  {
    id: "prosperity",
    company: "Prosperity Real Estate & Investment Services",
    role: "Technical Solutions Engineer",
    type: "Full-time",
    period: "Apr 2019 - Oct 2020",
    location: "On-site",
    isActive: false,
    responsibilities: [
      "Automated workflows and integrated third-party APIs",
      "Performed data extraction and transformation for internal operations",
      "Assisted in technical research and system optimization",
    ],
    technologies: ["APIs", "Automation", "Data Transformation"],
    relevance: "API integration, data transformation, technical research",
  },
];

export const languages = [
  { name: "English", level: "Fluent", percentage: 95 },
  { name: "Albanian", level: "Native", percentage: 100 },
  { name: "Italian", level: "Fluent", percentage: 90 },
  { name: "Spanish", level: "Intermediate", percentage: 60 },
  { name: "French", level: "Basic", percentage: 30 },
];

export const metrics = [
  {
    label: "Automation Success Rate",
    value: 98.7,
    suffix: "%",
    description: "Pipeline execution success",
  },
  {
    label: "Data Accuracy",
    value: 99.2,
    suffix: "%",
    description: "Validated output quality",
  },
  {
    label: "Pipeline Uptime",
    value: 99.9,
    suffix: "%",
    description: "System availability",
  },
  {
    label: "AI Evaluations",
    value: 150,
    suffix: "+",
    description: "Provider benchmarks completed",
  },
  {
    label: "Workflows Deployed",
    value: 200,
    suffix: "+",
    description: "Production automations",
  },
];

export const education = {
  degree: "Bachelor's Degree",
  field: "Computer Science / Engineering",
  institution: "South East European University (SEEU)",
  status: "Completed",
};

export const techStack = {
  languages: ["Python", "Node.js", "TypeScript", "PHP"],
  dataAutomation: ["pandas", "CSV/JSON processing", "web scraping", "APIs"],
  aiLlm: ["RAG pipelines", "AI evaluation frameworks", "orchestration"],
  tools: ["n8n", "REST APIs", "XML"],
  webAutomation: ["Selenium", "HTML parsing", "dynamic content handling"],
  visualization: ["matplotlib", "dashboards", "reporting"],
};

export const testimonials = [
  {
    id: 1,
    name: "larosacre",
    quote: "Awesome job, very quick and detailed on how to use the system and tools. I look forward to working with him on other projects. A++",
    rating: 5,
    country: "US",
  },
  {
    id: 2,
    name: "jaymillion",
    quote: "He was able to get my apps integrated and works perfectly. Definitely recommended and will work with again. A++",
    rating: 5,
    country: "US",
  },
  {
    id: 3,
    name: "robinharris408",
    quote: "A constant professional who totally over-delivered on all offers. I would definitely recommend his services.",
    rating: 5,
    country: "US",
  },
  {
    id: 4,
    name: "The Property Guys",
    quote: "Pleasure to work with and phenomenal communication skills. Highly recommended!",
    rating: 5,
    country: "CA",
  },
  {
    id: 5,
    name: "snozy3",
    quote: "VERY RELIABLE AND QUICK, big plans to work with him in the future.",
    rating: 5,
    country: "US",
  },
  {
    id: 6,
    name: "focusInvestment",
    quote: "Great response and turn around time.",
    rating: 5,
    country: "US",
  },
  {
    id: 7,
    name: "cistudios541",
    quote: "Fast seller. Was able to get the job done quickly and show us how the functionality works.",
    rating: 5,
    country: "US",
  },
  {
    id: 8,
    name: "arbquality",
    quote: "Delivered in a timely manner and communicated very well!",
    rating: 5,
    country: "US",
  },
  {
    id: 9,
    name: "mnowickimarda",
    quote: "It was great working together!",
    rating: 5,
    country: "CA",
  },
  {
    id: 10,
    name: "Ray (SATX Marketing)",
    quote: "Very easy to work with, great attention to detail. Definitely looking forward to doing business again!",
    rating: 5,
    country: "US",
  },
];

export const bootSequenceLines = [
  { text: "> Initializing Hybrid Agent System...", delay: 0 },
  { text: "> Loading AI Pipelines", dots: true, status: "OK", delay: 600 },
  { text: "> Connecting to Data Sources", dots: true, status: "OK", delay: 1200 },
  { text: "> Calibrating LLM Modules", dots: true, status: "OK", delay: 1800 },
  { text: "> Validating RAG Pipelines", dots: true, status: "OK", delay: 2400 },
  { text: "> Human-in-the-loop: ACTIVE", delay: 3000, highlight: true },
  { text: "> System Ready.", delay: 3600, final: true },
];
